# Build stage for .NET app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy published .NET app from build stage
COPY --from=build-env /app/out .

# Set environment variables
ENV ASPNETCORE_URLS=http://*:80

# Set entry point
ENTRYPOINT ["dotnet", "server.dll"]